baseURL: ''
languageCode: en-us
title: 'Carolyn Ho'
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          work: work
          play: play
          resume: resume
        menu:
            main:
                - name: Work
                  url: post/
                  weight: 3
                - name: Play
                  url: play2
                  weight: 6
                - name: Resume
                  url: resume2
        profileMode:
            enabled: true
            title: Hi there! 
            imageUrl: "https://user-images.githubusercontent.com/89154660/228745585-7465d8aa-e6d8-479f-80e1-ac40a4d3bd0c.svg"
            imageTitle: My Avatar
            subtitle: "I am a DesignerğŸ’», an Experience SeekerğŸ–¼ï¸, a Mom of OneğŸ¼. "
            buttons:
                - name: Work
                  url: post/
                - name: Let's chat
                  url: https://discord.gg/TjUNmZUNFP
    
    # ä¸­:
    #     languageName: "Chinese"
    #     languageAltTitle: Chinese
    #     weight: 2
    #     title: ä½•è·çš„ä½œå“é›†
    #     taxonomies:
    #       work: å·¥ä½œé–“
    #       play: éŠæ¨‚åœ’
    #       resume: ç°¡æ­·
    #     menu:
    #         main:
    #             - name: å·¥ä½œé–“
    #               url: ../work-cn
    #               weight: 3
    #             - name: éŠæ¨‚åœ’
    #               url: ../play.cn
    #               weight: 6
    #             - name: ç°¡æ­·
    #               url: ../resume.cn
    #     profileMode:
    #         enabled: true
    #         title: å—¨ï¼Œä½ å¥½! 
    #         imageUrl: "https://user-images.githubusercontent.com/89154660/228745585-7465d8aa-e6d8-479f-80e1-ac40a4d3bd0c.svg"
    #         imageTitle: My Avatar
    #         subtitle: "æˆ‘æ˜¯ä½•è·ï¼Œä¸€å€‹è¨­è¨ˆå¸«ğŸ’», ä¸€å€‹é«”é©—è¿½æ±‚å®¶ğŸ–¼ï¸, ä¹Ÿæ˜¯ä¸€å€‹æ–°æ‰‹é¤Šè‚²è€…ğŸ¼. "
    #         buttons:
    #             - name: æˆ‘çš„ä½œå“é›†
    #               url: ../work-cn
    #             - name: å®¢å®˜é€™é‚Šè«‹
    #               url: https://discord.gg/TjUNmZUNFP

params:
    defaultTheme: light
    profileMode:
        enabled: true
        subtitle: 'This is subtitle'
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        # buttons:
        #   - name: Github
        #     url: "https://github.com/"

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/ho-carolyn"
        - name: github
          url: "https://github.com/carolynho0422"
        - name: facebook
          url: "https://www.facebook.com/profile.php?id=100041670961919"
